apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: data-etl
  namespace: ng-spark
spec:
  arguments:
    - --packages=org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.4
  deps:
    jars:
      - https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.11/2.4.4/spark-sql-kafka-0-10_2.11-2.4.4.jar
      - https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
      - https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar
  type: Java
  mode: cluster
  sparkVersion: "2.4.4"
  image: "etl:latest"
  imagePullPolicy: Always
  mainClass: com.poc.spark.etl.AppRunner
  mainApplicationFile: local:///opt/spark-2.4.4/jars/etl-1.0-SNAPSHOT.jar
  restartPolicy:
    type: Never
  driver:
    cores: 2
    insatance: 1
    memory: "2048m"
    corelimit: "2048m"
    labels:
      version: 2.4.4
    serviceAccount: spark
  executor:
    cores: 2
    instances: 2
    memory: "2048m"
    labels:
      version: 2.4.4
